repos:
  - repo: local
    hooks:
      - id: terraspace-fmt
        name: Terraspace Format
        entry: bin/pre-commit-terraspace-fmt.sh
        language: system
        pass_filenames: false
        files: \.tf(vars)?$
