name: Cumulus
on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/**'
      - 'app/**'
      - '!app/stacks/cumulus/resources/**'
      - 'config/**'
      - 'src/**'
      - .nvmrc
      - .yarnrc
      - yarn.lock
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    branches:
      - main
    paths:
      - '.github/workflows/**'
      - 'app/**'
      - '!app/stacks/cumulus/resources/**'
      - 'config/**'
      - 'src/**'
      - .nvmrc
      - .yarnrc
      - yarn.lock

defaults:
  run:
    shell: bash

env:
  TF_IN_AUTOMATION: 1

jobs:
  plan-uat:
    # Run on PR actions on "source" (head) branches (not on main branch)
    if: github.event.ref != 'refs/heads/main'
    uses: ./.github/workflows/terraspace.yml
    with:
      TS_ENV: uat
      deploy: false
    secrets: inherit

  deploy-uat:
    # Run only on main branch (on push, including on merged PRs)
    if: github.event.ref == 'refs/heads/main'
    uses: ./.github/workflows/terraspace.yml
    with:
      TS_ENV: uat
      deploy: true
    secrets: inherit

  # deploy-prod:
  #   # Run only on main branch (on push, including on merged PRs)
  #   if: github.event.ref == 'refs/heads/main'
  #   needs: deploy-uat
  #   uses: ./.github/workflows/terraspace.yml
  #   with:
  #     TS_ENV: prod
  #     deploy: true
  #   secrets: inherit
