name: Cumulus
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed
    branches:
      - main

defaults:
  run:
    shell: bash

env:
  TF_IN_AUTOMATION: 1

jobs:
  plan-uat:
    if: github.event.pull_request.merged != true
    uses: ./.github/workflows/terraspace.yml
    with:
      TS_ENV: uat
      deploy: false
    secrets: inherit

  deploy-uat:
    if: github.event.pull_request.merged == true
    uses: ./.github/workflows/terraspace.yml
    with:
      TS_ENV: uat
      deploy: true
    secrets: inherit

  deploy-prod:
    needs: deploy-uat
    uses: ./.github/workflows/terraspace.yml
    with:
      TS_ENV: prod
      deploy: true
    secrets: inherit
