name: Cumulus
on:
  push:
    branches:
      - main
  workflow_dispatch:

defaults:
  run:
    shell: bash

env:
  TF_IN_AUTOMATION: 1

jobs:
  unit-tests:
    runs-on: ubuntu-20.04
    steps:
      - name: unit tests
        run: |
          echo "Nothing to unit test yet"

  # Intended only for locally testing development deployment job via `act`,
  # using the following command:
  #
  #     act --secret-file .env -j deploy-dev workflow_dispatch
  #
  deploy-dev:
    if: github.event_name == 'workflow_dispatch' && github.event.ref != 'refs/heads/main'
    needs: [unit-tests]
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Update packages list
        run: sudo apt-get update -y

      - name: Install tfenv
        run: |
          git clone https://github.com/tfutils/tfenv.git ${HOME}/.tfenv
          sudo ln -s ${HOME}/.tfenv/bin/* /usr/local/bin

      - name: Install Terraform
        run: tfenv install

      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Install Ruby and Bundler
        run: |
          sudo apt-get install -y ruby-full
          gem install bundler

      - name: Install Terraspace
        run: bundle install

      - name: Deploy Cumulus
        run: terraspace all plan

  deploy-uat:
    if: github.event_name == 'push' && github.event.ref == 'refs/heads/main'
    needs: [unit-tests]
    runs-on: ubuntu-20.04
    environment:
      name: uat
    env:
      TS_ENV: uat
    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Update package list
        run: sudo apt-get update -y

      - name: Install tfenv
        run: |
          git clone https://github.com/tfutils/tfenv.git ${HOME}/.tfenv
          rm -f /usr/local/bin/terraform
          sudo ln -s ${HOME}/.tfenv/bin/* /usr/local/bin

      - name: Install Terraform
        run: tfenv install

      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Install Ruby and Bundler
        run: |
          sudo apt-get install -y ruby-full
          gem install bundler

      - name: Install Terraspace
        run: bundle install

      - name: Deploy Cumulus
        run: terraspace all up --yes
